[ENTESB-16621] Add Indy Maven repository for io.prometheus.jmx:jmx_pr…
jboss-fuse/fuse-karaf pull request #430
Opened 2021-07-20 13:52 UTC by johnpoth

…ometheus_javaagent:jar:0.14.0.redhat-00002

2021-07-20 13:55 UTC, grgrzybek approved these changes

2021-07-20 13:55 UTC, merged

2021-07-20 14:25 UTC, oscerd requested changes
I don't think it is a good idea. It's slow and not reliable

2021-08-18 07:46 UTC, grgrzybek commented
oops. no protocol in indy URL.... Now I see strange build failures. Why did I miss that when approving? :)

2021-08-18 07:48 UTC, grgrzybek commented
@johnpoth @oscerd generally I'd like to remove indy from the pom. When building the project, indy should be added externally (for example using a profile defined in your `~/.m2/settings.xml`...